config/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path

from login import views
from boards import views as v_board

from blog.views import index

# accounts
from accounts import views as accounts_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home, name='home'),
    path('', v_board.home, name='home'),
    path('boards/<int:board_id>/', v_board.board_topics, name='board_topics'),
    path('boards/<int:board_id>/new', v_board.new_topic, name='new_topic'),
    path('boards/<int:pk>/topics/<int:topic_pk>/', v_board.topic_posts, name='topic_posts'),
    path('boards/<int:pk>/topics/<int:topic_pk>/reply/', v_board.reply_topic, name='reply_topic'),
    path('boards/<int:pk>/topics/<int:topic_pk>/posts/<int:post_pk>/edit/', v_board.PostUpdateView.as_view(), name='edit_post'),

    # acounts
    path('signup/', accounts_view.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),


    # reset password
    # path('reset/', auth_views.PasswordResetView.as_view(
    #     template_name='password_reset_html',
    #     email_template_name='password_reset_email.html',
    #     subject_template_name='password_reset_subject.txt'
    # ), name='password_reset'),
    # path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password-reset_done')),
    # path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password-reset_done')),

    # reset password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='password_reset.html',
                                                                 email_template_name='password_reset_email.html',
                                                                 subject_template_name='password_reset_subject.txt'), name='reset_password'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_complete'),

    # changed password once user is log in
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'), name='password_change'),
    path('settings/password/done', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),

]

boards/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='topics')
    starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='topics')
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='+')

login/models.py
from django.db import models

# Create your models here.

boards/forms.py
from django import forms
from .models import Topic, Post


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(), max_length=4000, help_text='The max length of the text is 4000')

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']

login/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

# def home(request):
#	return HttpResponse('Hello, World')

def home(request):
    return render(request, 'base.html')


class PostUpdateView:
    pass

templates/base.html
{% load static tailwind_tags tailwind_filters crispy_forms_tags %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en" xmlns:x-on="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %} {% endblock title %}</title>
    <!-- Favicon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Inter font -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet"/>

    <!-- flowbite styles -->
    <link rel="stylesheet" href="{% static 'css/flowbite.min.css' %}" />

    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    {% tailwind_css %}

    <style></style>
  </head>

  <body>
    <!-- Start your project here-->

    <!-- The header -->
      <header>
        <nav>
          <section class=" lg:px-7 px-2.5 py-1.5 bg-gray-800 shadow-md border-ml">
            <main class="flex items-center justify-between">
              <!-- Logo and menu -->
              <section class="flex items-center space-x-8">
                <!-- Logo -->
                <a href="javascript:void(0)">
                  <div class="flex items-center space-x-2">
                    <img src="{% static 'img/3305206_cactus_desert_hot_nature_sky_icon(1).png' %}" alt="logo" class="w-12 rounded object-cover">
                    <h2 class="text-sm lg:text-lg font-bold text-gray-200 capitalize tracking-wider header_title">Desert Inc.</h2>
                  </div>
                </a>
                <!-- menu -->
                <div class="lg:block hidden">
                  <ul class="flex items-center space-x-5">
                    <li class="active nav_link">
                      <a href="javascript:void()" class="text-md capitalize">
                        Dashboard
                      </a>
                    </li>

                    <li>
                      <a href="javascript:void(0)" class="text-md capitalize nav_link">
                        Team
                      </a>
                    </li>

                    <li>
                      <a href="javascript:void(0)" class="text-md capitalize nav_link">
                        Projects
                      </a>
                    </li>

                    <li>
                      <a href="javascript:void(0)" class="text-md capitalize nav_link">
                        Calendar
                      </a>
                    </li>
                  </ul>
                </div>
              </section>

              <!-- Search & notify & user-icon -->
              <section class="flex items-center space-x-5">
                <div>
                  <ul class="flex items-center space-x-4">
                    <!-- Search-->
                    <li class="lg:block hidden">
                      <div class="relative">
                        <div class="absolute left-1.5 top-1.5"><!--search icon -->
                          <svg class="w-6 h-6 text-gray-600" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z">
                            </path>
                          </svg>
                        </div>
                        <input type="search" class="w-full h-8 p-1 rounded-md bg-gray-700 focus:bg-gray-100 focus:ring ring-yellow-300 focus:outline-none pl-8" placeholder="Search">
                      </div>
                    </li>
                    <!--notify -->
                    {% if user.is_authenticated %}
                    <li class="mt-1">
                      <button class="focus:outline-none">
                        <svg id="Layer_2"  class="lg:w-6 lg:h-6 w-5 h-5 text-gray-400 hover:text-gray-200 focus:text-200" fill="none" stroke="white" viewBox="0 0 60 78"  xmlns="http://www.w3.org/2000/svg">
                          <title/><g id="Layer_2"><g id="Layer_3"><path d="M54.2,54.4l-5.1-6.3c-0.5-0.7-0.8-1.5-0.8-2.4v-13c0-8.1-5.4-15.3-13.2-17.5v-5.1c0-2.8-2.3-5-5-5s-5,2.3-5,5v5    c-7.9,2.3-13.3,9.5-13.2,17.6v13c0,0.9-0.3,1.7-0.8,2.4l-5.1,6.3c-0.4,0.5-0.7,1.2-0.7,1.9v7.9h49.8v-7.9    C54.9,55.6,54.6,54.9,54.2,54.4z M28,10.1c0-1.1,0.9-2,2-2s2,0.9,2,2v4.5c-1.4-0.2-2.7-0.2-4.1,0V10.1z M51.9,61.1H8.1v-4.8    l5.1-6.3c1-1.2,1.5-2.7,1.5-4.3v-13c0-8.4,6.8-15.3,15.3-15.3s15.3,6.8,15.3,15.3v13c0,1.6,0.5,3.1,1.5,4.3l5.1,6.3V61.1z"/><path d="M28,20.8v3c6.1,0,11.1,5,11.1,11.1c0,0,0,0,0,0h3C42.1,27.1,35.8,20.8,28,20.8C28,20.8,28,20.8,28,20.8z"/><path d="M30,69.9c-2.9,0-5.2-2.3-5.2-5.2h-3c0,4.5,3.7,8.2,8.2,8.2c4.5,0,8.2-3.7,8.2-8.2h-3C35.2,67.6,32.9,69.9,30,69.9z"/></g></g>
                        </svg>
                      </button>
                    </li>
                    <!-- user-icon -->
                    <li>
                      <!--<a href="javascript:void(0)" class="flex items-center space-x-2">
                        <img src="{% static 'img/403022_business man_male_user_avatar_profile_icon.png' %}" alt="user" class="w-7 object-cover rounded-full"> &lt;!&ndash;user icon &ndash;&gt;
                        <span class="font-xl text-white">{{ user.username }}</span>
                      </a>-->
                      <button id="dropdownInformationButton" data-dropdown-toggle="dropdownInformation" class="text-white bg-blue-700 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center" type="button"><a href="javascript:void(0)" class="flex items-center space-x-2">
                        <img src="{% static 'img/403022_business man_male_user_avatar_profile_icon.png' %}" alt="user" class="w-7 object-cover rounded-full"> <!--user icon -->
                        <span class="font-xl text-white">{{ user.username }}</span>
                      </a></button>
                      <!-- Dropdown menu -->
                      <div id="dropdownInformation" class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                        <div class="py-3 px-4 text-sm text-gray-900 dark:text-white">
                          <div>{{ user.username }}</div>
                          <div class="font-medium truncate">{{ user.email }}</div>
                        </div>
                        <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownInformationButton">
                          <li>
                            <a href="#" class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">My account</a>
                          </li>
                          <li>
                            <a href="{% url 'password_change' %}" class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Change password</a>
                          </li>
                        </ul>
                        <div class="py-1">
                          <a href="{% url 'logout' %}" class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
                        </div>
                      </div>
                    </li>
                    {% else %}
                    <li>
                        <ul class="flex items-center space-x-5" aria-labelledby="dropdownInformationButton">
                          <li>
                            <a href="{% url 'login' %}" class=" rounded-md text-md capitalize text-white border-2 border-gray-700 py-1 px-2 ">Login</a>
                          </li>
                          <li>
                            <a href="{% url 'signup' %}" class="rounded-md text-md capitalize text-white border-2 border-gray-700 py-1 px-2">Signup</a>
                          </li>
                        </ul>
                    </li>
                    {% endif %}
                    <!-- mobile button-->
                    <li class="lg:hidden block">
                      <button class="focus:outline-none focus:bg-gray-800 w-7 h-7 p-1 rounded focus:ring ring-yellow-300 ring-opacity-50" onclick="mobMenu()">
                        <svg xmlns="http://www.w3.org/2000/svg" class="lg:w-6 lg:h-6 w-6 h-6 text-gray-400 hover:text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path id="bar" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h6"/>
                          <path id="close_bar" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                        </svg>
                      </button>
                    </li>
                  </ul>
                </div>
              </section>
            </main>
          </section>

          <!-- mobile_nav-->
          <section class="lg:hidden block bg-yellow-100 p-4 space-y-4 hidden" id="menu">
            <div>
              <ul class="flex flex-col space-y-5">
                <li class="active nav_link">
                  <a href="javascript:void(0)" class="text-md capitalize text-gray-500 hover:text-yellow-500 nav_link">Dashboard</a>
                </li>
                <li>
                  <a href="javascript:void(0)" class="text-md capitalize text-gray-500 hover:text-yellow-500 nav_link">Team</a>
                </li>
                <li>
                  <a href="javascript:void(0)" class="text-md capitalize text-gray-500 hover:text-yellow-500 nav_link">Projects</a>
                </li>
                <li>
                  <a href="javascript:void(0)" class="text-md capitalize text-gray-500 hover:text-yellow-500 nav_link">Calendar</a>
                </li>
              </ul>
            </div>

            <!-- mobile Search Bar-->
            <section class="w-full">
              <div class="relative">
                <div class="absolute left-1.5 top-1.5">
                  <svg class="w-5 h-5 text-gray-300" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z">
                    </path>
                  </svg>
                </div>
                <input class="w-full h-8 p-1 rounded-md border border-gray-300 focus:ring ring-yellow-300 ring-opacity-75 focus:outline-none pl-8" type="search" placeholder="search">
              </div>
            </section>
          </section>
        </nav>
      </header>

      <section class="container mx-auto">
        <p class="p-7">
          <div class="container flex justify-center mx-auto">
            <div class="w-full p-3 bg-gray-100">
                <ol class="flex items-center text-blue-800">
                  {% block breadcrumbs %}
                  {% endblock breadcrumbs %}
                </ol>
            </div>
          </div>
        </p>
        <p class="p-2">
          {% block content %}
          {% endblock content %}
        </p>
      </section>

    <!-- End your project here-->
    <!-- Tailwind Elements JS -->
    <script type="text/javascript" src="{% static 'js/index.min.js' %}"></script>

    <!-- JQuery CDN -->
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

    <!-- flowbite JS -->
    <script src="{% static 'js/flowbite.js' %}"></script>

    <!-- Custom scripts -->
    <script>
      const navLink = document.querySelectorAll('.nav_link');

      function LinkAct(){
        navLink.forEach(n => n.classList.remove('active'));
        this.classList.add('active');
      }

      navLink.forEach(n => n.addEventListener('click', LinkAct));

      function mobMenu() {
        if($("#menu").hasClass("hidden") ){
          $("#menu").removeClass("hidden");
          $("#bar").css({display: "none"});
          $("#close_bar").css({display: "block"});
        }
        else {
          $("#menu").addClass("hidden");
          $("#bar").css({display: "block"});
          $("#close_bar").css({display: "none"});
        }
      }
    </script>
  </body>
</html>

templates/brouillon.html
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque enim, excepturi ipsam modi molestias quis unde. Autem distinctio dolorem ducimus et, incidunt, ipsum iusto magnam officia porro sed tempore, voluptatem.

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Boards Page
{% endblock title %}

{% block breadcrumbs %}
    <li class="flex items-center ml-1">
        <a href="{% url 'home' %}" class="font-bold">Boards</a>
        <!-- <span class="ml-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
        </span> -->
    </li>
{% endblock breadcrumbs %}

{% block content %}
    <table class="w-full">
        <thead class="bg-gray-800 text-white h-12">
            <tr class="">
                <th class="text-left pl-2">Board</th>
                <th>Posts</th>
                <th>Topics</th>
                <th>Last Post</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
            <tr  class="border-b border-gray-400 h-20">
                <td class="pl-2">
                    <a href="{% url 'board_topics' board.id %}" class="text-blue-900 font-bold">{{ board.name }}</a>  <br>
                    <small class="text-gray-700">{{ board.description }}</small>
                </td>
                <td class="border-b border-gray-400 text-center">{{ board.topics.count }}</td>
                <td class="border-b border-gray-400 text-center">{{ board.get_posts_count }}</td>
                <td class="border-b border-gray-400 text-center">
                    {% with post=board.get_last_post %}
                        {% if post %}
                            <small>
                                <a href="{% url 'topic_posts' board.id post.topic.pk %}">
                                    By {{ post.created_by.username }} at {{ post.created_at }}
                                </a>
                            </small>
                         {% else %}
                            <small>
                                <em>No posts yet.</em>
                            </small>
                        {% endif %}
                    {% endwith %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Login Page
{% endblock title %}

{% block content %}
<div class="p-4 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 lg:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <h5 class="text-xl font-medium text-gray-900 dark:text-white">Login</h5>
        {% include 'includes/form.html' %}
        <button type="submit" class="w-full items-center mt-2 px-6 py-2 text-sm text-white bg-blue-600 rounded hover:bg-blue-700">Login</button>
        <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
            New to Django Boards? <a href="{% url 'signup' %}" class="text-blue-700 hover:underline dark:text-blue-500">Sign Up</a>
        </div>
        <div>
            <small>
                <a href="{% url 'reset_password' %}">Forgot your password</a>
            </small>
        </div>
    </form>
</div>
{% endblock content %}

templates/new_topic.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Topic Page
{% endblock title %}

{% block breadcrumbs %}
    <li class="flex items-center ml-1">
        <a href="{% url 'home' %}" class="font-bold">Boards</a>
        <span class="ml-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
        </span>
    </li>
    <li class="flex items-center ml-1">
        <a href="{% url 'board_topics' board.id %}" class="font-bold">{{ board.name }}</a>
        <span class="ml-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
        </span>
    </li>
    <li class="flex items-center ml-1">
        <a href="#" class="font-bold text-gray-500">New Topic</a>
    </li>
{% endblock breadcrumbs %}

{% block content %}
<!--    <form action="" method="post">
        {% csrf_token %}
        <div>
            <label for="id_subject" class="block mb-2 text-sm text-gray-600">Subject</label>
            <input type="text" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300" id="id_subject" name="subject">
        </div>
        <div>
            <label for="id_message" class="block mt-4 mb-2 text-sm text-gray-600">Message</label>
            <textarea type="text" class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300" id="id_message" name="message" rows="5"></textarea>
        </div>
        <button type="submit" class="inline-flex items-center mt-2 px-6 py-2 text-sm text-white bg-green-600 rounded hover:bg-green-700">Post</button>
    </form>-->

<!--    <form method="post" novalidate>
        {% csrf_token %}
        {% crispy form%}
        <input type="submit" class="py-1 px-3 my-4 bg-green-500 text-white font-medium rounded hover:bg-indigo-500 cursor-pointer ease-in-out duration-300" value="Post">
    </form>-->

<!--    <form method="post" novalidate>
        {% csrf_token %}
&lt;!&ndash;        {% crispy form%}&ndash;&gt;
        {% for field in form %}
            <div class="block mb-2 text-sm text-gray-600">
                {{ field.label_tag }}
                {% render_field field class="w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300" %}
                {% if field.help_text %}
                    <small class="text-xs">
                        {{ field.help_text }}
                    </small>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="inline-flex items-center mt-2 px-6 py-2 text-sm text-white bg-green-600 rounded hover:bg-green-700">Post</button>
    </form>-->

<!--    <form method="post" novalidate>
        {% csrf_token %}

        {%for field in form %}
            <div class="">
                {{ field.label_tag }}

                {% if form.is_bound %}
                    {% if field_errors %}
                        {% render_field field class="border-2 border-red-700" %}
                        {% for error in field.errors %}
                            <div class="inline-flex text-sm text-red-700">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="border-4 border-blue-700" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="border-4 border-blue-700" %}
                {% endif %}

                {% if field.help_text %}
                    <small class="text-xs">
                        {{ field.help_text }}
                    </small>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="inline-flex items-center mt-2 px-6 py-2 text-sm text-white bg-green-600 rounded hover:bg-green-700">Post</button>
    </form>-->

  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="inline-flex items-center mt-2 px-6 py-1 text-sm text-white bg-green-600 rounded hover:bg-green-700">Post</button>
  </form>
{% endblock content %}

templates/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Login Page
{% endblock title %}

{% block breadcrumbs %}
    <li class="flex items-center ml-1">
        <a href="{% url 'home' %}" class="font-bold">Change password</a>
        <!-- <span class="ml-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
        </span> -->
    </li>
{% endblock breadcrumbs %}

{% block content %}
<div class="p-4 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 lg:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="w-full items-center mt-2 px-6 py-2 text-sm text-white bg-blue-600 rounded hover:bg-blue-700">Change password</button>
    </form>
</div>
{% endblock content %}

templates/password_reset.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Reset Password
{% endblock %}

{% block content %}
    <h3>Pour reinitialiser votre mot de passe entrer votre adresse email</h3>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="w-full items-center mt-2 px-6 py-2 text-sm text-white bg-blue-600 rounded hover:bg-blue-700">Send email</button>
    </form>
{% endblock %}

templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email addresss {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the url in a new browser window instead.

If you've received this mail in error, it's likely that another user entered your email address by mistake
while trying to reset a password. If you didn't initiate the request, you don't need to take any further action
and can safely disregard this email.

Thanks,

The Django Boards Team

templates/password_reset_sent.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Reset Password
{% endblock %}

{% block content %}
    <h3>Consulter votre boite email pour reinitialiser votre mot de passe</h3>
{% endblock %}